#!/bin/bash

APP_ARGS=$*

# Execute Java with arguments in the correct order
# The 'exec' command replaces the current shell process, improving resource usage.
exec java -Djava.awt.headless=true -Ddevelopment=false -jar /app/juicer_tools.jar $APP_ARGS
